apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}'
    io.giantswarm.application.team: '{{ index .Chart.Annotations "io.giantswarm.application.team"
      }}'
  name: capi-kamaji-controller-manager
  namespace: '{{ .Release.Namespace }}'
spec:
  egress:
  - toEntities:
    - kube-apiserver
  endpointSelector:
    matchLabels:
      cluster.x-k8s.io/provider: kamaji
  ingress:
  - fromEntities:
    - cluster
    - kube-apiserver
