apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-api-control-plane-provider-kamaji
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/part-of: cluster-api-control-plane-provider-kamaji
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    cluster.x-k8s.io/provider: kamaji
    helm.sh/chart: '{{ .Chart.Name }}'
    io.giantswarm.application.team: '{{ index .Chart.Annotations "io.giantswarm.application.team"
      | quote }}'
  name: capi-kamaji-controller-manager
  namespace: '{{ .Release.Namespace }}'
