image:
  name: giantswarm/cluster-api-control-plane-provider-kamaji
  repository: gsoci.azurecr.io
  tag: PLACEHOLDER

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 64Mi
